// Generated by CoffeeScript 1.9.3
(function() {
  this.toggleIssueDedupe = function(element) {
    var dedupe;
    dedupe = element.checked;
    return window.location = window.location.pathname + (dedupe ? '?dedupe=1' : '');
  };

}).call(this);
